config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :events, :voters
  get 'notify(/:id)', to: 'voters#notify', as: 'notify'
  get 'next(/:id)', to: 'events#next', as: 'next'

  # Defines the root path route ("/")
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId
  validates :title, length: { in: 2..100 }
  validates :description, length: { in: 0..200 }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :minimum, presence: true

  has_many :voters
  has_many :voters_with_email, -> { where.not(email: '') }, class_name: 'Voter'

  has_many :votes
  friendly_id :slug_candidates, use: :slugged

  before_validation :clean_inputs, only: %i[title description]

  def days
    arr = []
    (start_date..end_date).each.map { |day| arr << { start_date: day, end_date: day } }
    arr.map { |hsh| OpenStruct.new(hsh) }
  end

  def email_list(id)
    event = Event.find(id)
    event.voters_with_email
  end

  def majority(id)
    vote_query = Event.where(id:).joins(:votes).group('events.id').group('votes.day').count
    sorted_days = vote_query.sort.sort_by { |_date, count| count }.reverse.to_a
    begin
      max = sorted_days.first[1]
    rescue StandardError
      sorted_days
    else
      sorted_days.select { |day| day[1] >= max }.reverse
    end
  end

  def slug_candidates
    [
      [random_prefix, :title],
      [random_monster, :title],
      %i[title end_date],
      [random_prefix, :title, :end_date],
      [random_monster, :title, :end_date]
    ]
  end

  private

  def random_monster
    monsters = %w[ aboleth yeti chicken acererak acolyte dragon ankheg assassin azer basilisk behir dog
                   bugbear centaur chuul cockatrice chimera dryad dwarf gorgon gargoyle genie ghost ghoul giant
                   gnoll gnome golem goblin ogre ooze owlbear owl orc griffon halflings harpy satyr cat bat bison boar
                   phasm hydra howler hobgoblin hippogriff homunculus howler kobold kraken lich lycanthorpe duergar
                   roc sprite lizardfolk elf]
    monsters.sample
  end

  def random_prefix
    prefixes = %w[ youre-invited-to welcome-to a-kingly-invite-to attention twitch-presents a-personal-invite-to
                   attention-adventurers my-lord-of-thicc]
    prefixes.sample
  end

  def clean_inputs
    self.title = title.delete("\000") unless title.nil?
    self.description = description.delete("\000") unless description.nil?
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  validates_presence_of :day
  belongs_to :voter
  belongs_to :event
end

app/models/voter.rb
class Voter < ApplicationRecord
  after_create :check_if_minimum_met
  after_update :check_if_minimum_met

  validates :name, presence: true, uniqueness: { scope: :event_id, case_sensitive: false }
  validates_length_of :name, minimum: 1, message: 'is too short (minimum is 1 character)'
  validates_length_of :name, maximum: 26, message: 'is too long (maximum is 26 characters)'

  validates :email, allow_nil: true, uniqueness: { scope: :event_id }, format: { with: URI::MailTo::EMAIL_REGEXP }

  belongs_to :event
  has_many :votes

  accepts_nested_attributes_for :votes, allow_destroy: true, reject_if: proc { |vote|
                                                                          true unless vote.key?('day')
                                                                        }

  private

  def check_if_minimum_met
    event = Event.find_by(id: event_id)
    voters = event.voters.count
    minimum = event.minimum
    NotifyEmailJob.new.email_event_members(event_id) if voters >= minimum
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def render_flash
    turbo_stream_update('flash', partial: 'shared/flash')
    render turbo_stream: actions
  end

  def update_friends
    turbo_stream_update('friends', action: 'prepend', partial: 'events/friends_joined')
    turbo_stream_update('flash', partial: 'shared/flash')
    turbo_stream_update('votes', partial: 'events/event_info')
    turbo_stream_update('forms', partial: 'voters/notify')
    render turbo_stream: actions
  end

  def turbo_stream_update(key, component)
    @turbo_stream_actions ||= []
    @turbo_stream_actions << turbo_stream.update(key, view_context.render(component))
  end

  def actions
    @turbo_stream_actions
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def index; end

  def create
    @event = Event.create(event_params)

    respond_to do |format|
      if @event.save
        flash[:success] = 'One step closer!'
        format.html { redirect_to @event }
      else
        flash.now[:error] = 'Something went wrong D:'
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render_flash }
      end
    end
  end

  def show
    @event = Event.friendly.find(params[:id])
    @voter = Voter.new
  end

  def notify
    @event = Event.friendly.find(params[:id])
    @voter = Voter.find(cookies[:voter_id])
  end

  def next
    @event = Event.friendly.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :minimum, :start_date, :end_date)
  end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  def new; end

  def notify
    @voter = Voter.find(cookies[:voter_id])
  end

  def create
    @event = Event.friendly.find(params[:voter][:event_id])
    @voter = @event.voters.create(voter_params)

    respond_to do |format|
      if @voter.save
        cookies[:voter_id] = @voter.id
        flash.now[:success] = 'New party member added!'
        format.turbo_stream { update_friends }
        format.html { redirect_to notify_path(@voter) }
        format.json { render json: @voter, status: :ok }
      else
        flash.now[:error] = 'Something went wrong! D: '
        format.turbo_stream { render_flash }
        format.html { redirect_to event_path(@event) }
        format.json { render json: @voter.errors, status: unprocessable_entity }
      end
    end
  end

  def update
    @voter = Voter.find(cookies[:voter_id])
    @event = Event.friendly.find(@voter.event_id)

    respond_to do |format|
      if @voter.update(voter_params)
        flash[:success] = 'Email added'
        format.html { redirect_to next_path(@event) }
      else
        flash[:error] = 'Email failed'
        format.turbo_stream { render_flash }
        format.html { redirect_to notify_path(@voter) }
      end
    end
  end

  private

  def voter_params
    params.require(:voter).permit(:name, :event_id, :email,
                                  votes_attributes: %i[day _destroy event_id voter_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/events/_event_info.html.haml
.card.bg-white.justify-center.items-center.p-5.w-full.gap-1.flex.flex-col
  .card-body
    .card-title
    .flex.flex-col.justify-start.items-start.text-left.w-full.gap-1
      %h1.text-2xl.font-lexend.font-bold.text-black.text-left{ data: {test_id: "event_title"} }
        = title @event.title
      %p.text-lg.font-inter.text-gray.font-regular{ data: {test_id: "event_description"} }
        = description @event.description
      - min = @event.minimum
      - count = @event.voters.count
      - remaining = min - count
      - case
      - when remaining > 1
        %p.text-md.font-lexend.font-bold.text-gray-400
          Waiting on
          = remaining.humanize
          = "friend".pluralize(remaining)
      - when remaining == 1
        %p.text-md.font-lexend.font-bold.text-gray-400
          Waiting on one more!
      - when remaining == 0
        %p.text-md.font-lexend.font-bold.text-gray-400
          = "The party of #{min.humanize} is here!"
      - else
        %p.text-md.font-lexend.font-bold.text-gray-400
          = "Expected #{min.humanize} people to join. Now we have #{count.abs.humanize}!"
  .flex.flex-col.justify-center.items-start.gap-2
    - days = @event.majority(@event.id)
    - if  days.empty? || days.nil?
    - else
      - days.each do | vote |
        - break unless vote[1] >= 2
        .stats.w-auto.flex.flex-col.justify-center
          .stat.bg-gray-200.flex.flex-row.rounded-lg.p-4.px-16.w-80.align-center.items-center.justify-end
            %span.stat-value.text-lg.font-rubik.text-black= Date.parse(vote[0].to_s).strftime("%A %b, %d")
            %span.stat-figure.justify-center.flex-col.flex.items-center
              .flex.justify-center.items-center.flex-grow-0.flex-shrink-0.w-7.h-7{:class => "rounded-[360px] bg-[#f77]"}
                .text-white.font-bold.font-baloo= vote[1]

app/views/events/_friends_joined.html.haml
.card.bg-white.flex.flex-col.justify-center.gap-4.p-4
  - if @event.voters.empty?
    .card-title.justify-center
      %p.text-lg.font-inter.text-gray-400.py-4 Responses will appear here.
  - else
    .card-title.justify-center
      %p.font-inter.text-black
        - friends = @event.voters.count
        = friends.humanize.titleize
        = "friend".pluralize(friends)
        joined
    .card-content.px-2
      - @event.voters.includes([:votes]).each do | voter |
        %p.font-inter.text-gray-400
          = "#{voter.name} has joined."
          - voter.votes.each do | vote |
            = vote.day.strftime("%a")

app/views/events/_steps.html.haml
.text-center.py-2{ :data => {"controller": "steps" }}
  %ul#steps.steps{:data => { action: "turbo:load@document->steps#updateSteps",
            "steps-target": "stepsList",
            "steps-step-param": "#{@step}"} }
    %li.text-white.font-bold.font-rubik.text-md.step Plan Event
    %li.text-white.font-bold.font-rubik.text-md.step Tap Days
    %li#last.text-white.font-bold.font-rubik.text-md.step Send Email

app/views/events/index.html.haml
.max-h-screen.min-h-screen
  .hero.h-screen.pt-40.flex.flex-col.gap-10
    .flex.flex-col.text-center#hero-info.gap-8.pb-0
      %h1.font-lexend.font-bold.text-black.text-4xl.lg:text-5xl
        Defeat Scheduling
      %h2.text-xl.flex.flex-col.text-center.lg:text-3xl
        %span.font-inter.font-bold.text-white
          Find Everyone’s Availability
        %span.font-inter.font-bold.text-black
          in 10 seconds
    %a.btn.btn-accent.font-inter.font-bold.text-white.lg:text-2xl.lg:btn-lg{:href => new_event_path}
      Plan a Session

app/views/events/new.html.haml
.min-h-screen.justify-start
  = render "steps", locals: { step: @step = 0}
  .hero.lg:p-20
    .hero-content.flex-col
      .flex.flex-col.lg:flex-row.justify-center.gap-4
        .text-center.lg:text-left.w-50.card.bg-white.p-8.hidden.lg:flex
          %h1.lg:text-5xl.text-base-100.font-inter.font-bold Create your event
          %h2.lg:text-2xl.py-6.text-base-300.font-inter.font-bold.break-normal
            Fill out the name of your event.
          %h2.lg:text-2xl.py-6.text-base-300.font-inter.font-bold.break-normal
            Find out who's free this week or this month.
        .card.flex.flex-col.justify-center.items-center.bg-white.rounded-md.w-full.p-4
          = form_for :event, url: events_path, html: {class: "form"} do |form|
            .card-body.gap-4
              = form.hidden_field :start_date, value: Date.today
              .form-control.flex.flex-col.w-full.gap-1
                %label.text-2xl.font-inter.text-gray-400 You're invited to...
                = form.text_field :title, class: "input bg-gray-200 font-inter",
                  data: { test_id: 'title_field' }, placeholder: "D&D Session"
              .form-control.flex.flex-col.w-full.gap-1
                %label.text-2xl.font-inter.text-gray-400 What's it about?
                = form.text_field :description, class: "input bg-gray-200 font-inter",
                  data: { test_id: 'description_field' }, placeholder: "Time to fight the final boss"
              .form-control.flex.flex-col.w-full.gap-1
                %label.text-2xl.font-inter.text-gray-400 How many to expect?
                = form.range_field :minimum, max: "6", min: "2", type: "range", value: "3",
                  data: { test_id: 'minimum_field' },
                  class: "bg-primary range"

                .w-full.flex.justify-between.text-xs.px-2.font-rubik
                  %span
                    2
                  %span
                    3
                  %span
                    4
                  %span
                    5
                  %span
                    6
              .form-control.flex.flex-col.w-full.gap-1
                %label.text-2xl.font-inter.text-gray-400 How far into the future?
                .flex.flex-row.bg-slate-100.justify-center.gap-2.rounded-md.w-full.py-1
                  = form.button "Week", class: "btn btn-accent px-8 font-bold font-inter text-white", id: "event_end_date", name: "event[end_date]",
                    data: { test_id: "week_event" }, value: Date.today + 6
                  = form.button "Month", class: "btn btn-accent px-8 font-bold font-inter text-white", id: "event_end_date", name: "event[end_date]",
                    data: { test_id: "month_event" }, value: Date.today + 30

app/views/events/next.html.haml
%turbo-frame#forms{ :data => {"controller": "steps forms links", "turbo-action": "advance", "target": "_top"}}
  .card.flex.flex-col.justify-center.items-center.bg-white.rounded-md.w-full.p-4
    .card-body
      .card-title
        %p.font-inter.text-gray.text-md.font-regular.text-center
          Invite your friends
      .card-content
        %p.text-md.font-lexend.font-bold.text-gray-400
          You'll be notified when everyone has joined.
      .card-actions.justify-end.flex.flex-row.justify-start.items-start.text-left.w-full.gap-1
        %button.btn.btn-full.btn-primary{ data: { action: "click->links#copy", "links-target": "button"}, value: "#{event_url(@event.friendly_id)}"}
          Copy to Clipboard

app/views/events/show.html.haml
.bg-primary.flex.flex-col.gap-4.px-2.lg:px-80.overflow-auto{ :data => {"controller": "steps" }}
  = render "steps", locals: { step: @step = 1}
  %turbo-frame#votes
    = render "event_info", local: { event: @event }
  %turbo-frame#forms{ :data => { "controller": "forms"} }
    = render "voters/form", local: { voter: @voter }
  %turbo-frame#friends
    = render "friends_joined", local: { event: @event }

app/views/layouts/application.html.haml
!!!
%html{"data-theme" => "safe"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    / Google Tag Manager
    :javascript
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                                                                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                                                                                                          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                                                                                                            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
           })(window,document,'script','dataLayer','GTM-585PPVS');
    / End Google Tag Manager
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    - set_meta_tags description: "A free scheduling site for friends groups. Find everyone's availability with no login required."
    = display_meta_tags site: 'WhenAreWeFree?'
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", defer: true
    = favicon_link_tag ("favicon.ico")
    %meta{:content => "#da532c", :name => "msapplication-TileColor"}/
    %meta{:content => "#ffffff", :name => "theme-color"}/
  %body.max-h-screen.min-h-screen.bg-primary
    %turbo-frame#flash.fixed.top-0.left-0.right-0.w-full.md:w-60
      = render "shared/flash"
    .navbar
      .flex-1
        %a.font-baloo.font-bold.text-xl.btn.btn-ghost.lowercase{ :href => root_path }
          whenarewefree?
      .flex-none.dropdown.dropdown-end
        %label.btn.btn-square.btn-ghost{ :tabindex => "0" }
          %svg.inline-block.w-5.h-5.stroke-current{:fill => "none", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
            %path{:d => "M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
        %ul.dropdown-content.menu.p-2.shadow.bg-primary-200.rounded-box.w-52.mt-4{ :tabindex => "0" }
          %li
            %a.font-rubik.font-medium.text-white{ :href => new_event_path}
              Schedule something
    = yield

app/views/shared/_flash.html.haml
- flash.each do |type, msg|
  .alert.shadow-lg.relative.rounded-box.justify-center.align-center.flex-row.md:flex-row.md:w-60{ :class => "alert-#{type}",
         :data => { "controller": "flash" }}
    - if type == "success"
      %svg.stroke-current.flex-shrink-0.h-6.w-6{:fill => "none", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
    - elsif type == "error"
      %svg.stroke-current.flex-shrink-0.h-6.w-6{:fill => "none", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
    %span
      = msg

app/views/simple_calendar/_calendar.html.haml
.simple-calendar.p-1
  %span.calendar-title.font-rubik.lg:text-lg
    = t('date.abbr_month_names')[start_date.month]
    = start_date.year
  %table.table-auto.table-striped.text-center.lg:text-xl
    %thead.text-center
      %tr
        - date_range.slice(0, 7).each do |day|
          %th.font-rubik.text-gray-400.font-bold= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        = content_tag :tr, class: calendar.tr_classes_for(week) do
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_month_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    %span.calendar-title
      = t('date.month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_week_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    - if calendar.number_of_weeks == 1
      %span.calendar-title
        = t('simple_calendar.week', default: 'Week')
        = calendar.week_number
    - else
      %span.calendar-title
        = t('simple_calendar.week', default: 'Week')
        = calendar.week_number
        \- #{calendar.end_week}
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])

app/views/voters/_form.html.haml
.card.bg-white.flex.flex-col{ :data => {"controller": "steps forms links"} }
  .card-body
    .card-title
      %p.font-inter.text-gray.text-md.font-regular.text-center
        Tap the days you're free
    = form_with model: @voter do | form |
      = form.hidden_field :event_id, value: @event.id
      = turbo_frame_tag @voter do
        = form.fields_for "votes_attributes[]", Vote.new do |vote_form|
          = render partial: "voters/votes", locals: { event: @event, form: form, vote_form: vote_form}
          .mt-2.flex.flex-col.justify-center.items-center.gap-1.px-4.rounded-lg.bg-white
            .form-control.flex-col.gap-2
              = form.text_field :name, data: {test_id: "name" }, class: "input lg:input-lg input-ghost input-bordered input-md", placeholder: "Type name here..."
              = form.button "Submit Your Availability", data: { test_id: "submit", action: "turbo:submit-end->forms#redirect"}, class: "btn btn-primary"

app/views/voters/_notify.html.haml
%turbo-frame#forms{ :data => {"controller": "steps forms links" }}
  .card.flex.flex-col.justify-center.items-center.bg-white.rounded-md.w-full.p-4{:data => { action: "turbo:frame-load@document->steps#updateLastStep"}}
    = form_with model: @voter, url: voter_url(@voter), method: :patch, local: true do | form |
      .card-body.gap-4
        .form-control.flex.flex-col.w-full.gap-1
          %label.text-2xl.font-inter.text-gray-400 Share your email...
          = form.text_field :email, data: {test_id: "email" }, class: "input lg:input-lg input-ghost input-bordered input-md", placeholder: "Type email here..."
          = form.button "Submit Email", data: { test_id: "submit", action: "turbo:submit-end->forms#redirect"}, class: "btn btn-primary"

app/views/voters/_votes.html.haml
.my-1.flex.flex-col.justify-center.items-center.flex-grow.gap-1.px-4.rounded-lg.bg-white
  = calendar(start_date: @event.start_date, number_of_days: @event.days.count) do |date|
    .flex.justify-center.items-center.flex-grow-0.flex-shrink-0.relative.p-1
      %label.swap.swap-rotate.lg:p-2
        / this hidden checkbox controls the state
        = vote_form.check_box :_destroy, checked: true, data: { test_id: "calendar_day"}, id: date
        .swap-on.justify-center.items-center.flex-grow-0.flex-shrink-0.relative
          %span.font-rubik.text-primary-200.font-bold.text-right{:class => "w-[299px] h-[24.83px] text-[#537d6c]"}
            = date.strftime("%d")
        / checkmark icon
        %svg.swap-off.stroke-green-300.w-10.h-10{:fill => "none", :stroke => "currentColor", "stroke-width" => "2", :viewbox => "0 0 24 24", :xmlns => "https://www.w3.org/2000/svg"}
          %path{:d => "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
        = vote_form.hidden_field :day, value: date
        = vote_form.hidden_field :voter_id, value: @voter.id
        = vote_form.hidden_field :event_id, value: @event.id

app/views/voters/notify.html.haml
%turbo-frame#forms{ :data => {"controller": "steps forms links" }}
  .card.flex.flex-col.justify-center.items-center.bg-white.rounded-md.w-full.p-4{:data => { action: "turbo:frame-load@document->steps#updateLastStep"}}
    = form_with model: @voter, url: voter_url(@voter), method: :patch, local: true do | form |
      .card-body.gap-4
        .form-control.flex.flex-col.w-full.gap-1
          %label.text-2xl.font-inter.text-gray-400 Share your email...
          = form.text_field :email, data: {test_id: "email" }, class: "input lg:input-lg input-ghost input-bordered input-md", placeholder: "Type email here..."
          = form.button "Submit Email", data: { test_id: "submit", action: "turbo:submit-end->forms#redirect"}, class: "btn btn-primary"